### PR TITLE
Adding instructions for MacOS X users

### PR DESCRIPTION
**Pull request by andrsd**
Instructions that should help MacOS X users to get going with BeeRef.

### CODE REVIEW

**Comment by andrsd** [comment]
@rbreu Here are the promised instructions for Mac OS X users. I kept them to minimum - I don't like when people have to sift through tons of text. I put them on an individual page and linked them from the Installation section on the front page.

Let me know if you wish to make any changes.

**Comment by rbreu** [comment]
Thanks, I'll look into it when I'm back from vacation!

**Comment by andrsd** [comment]
Yeah, no problem. Enjoy your vacation! :+1:

**Comment by rbreu** [comment]
Okay, this is looking good! Since everything committed to the repo will be live immediately, I'm going to wait with the merge until I make a new release, roughly the coming weekend. Then we'll have the new pyinstaller builds for download so I can update the other instructions accordingly, and everything fits together.

**Comment by andrsd** [comment]
Sounds good 👍

**Pull request merged**
